added 2s-AGCN implementation
benedekrozemberczki/pytorch_geometric_temporal pull request #71
Opened 2021-06-05 16:06 UTC by alexriedel1

Added this implementation https://github.com/lshiwjx/2s-AGCN of Two-Stream Adaptive Graph Convolutional Networks for Skeleton-Based Action Recognition https://arxiv.org/abs/1805.07694

2021-06-05 16:10 UTC, alexriedel1 commented
Don't be too harsh it's my first pull request on github ever 😂

2021-06-05 21:45 UTC, benedekrozemberczki requested changes
Dear Alex, 

🎇 Thank you for contributing! It is really appreciated, do not worry - it is a really high quality contribution 👍. Please check the following things (you will have to add modifications in a number of places, not just the py file):

- Modify the init file of attention models.
- Run through your py file pylint.
- The docstring should contain default hyperparameter values e.g. kernel_size: int=9.
- Please write tests in the test folder.
- Add the paper to the readme - give reference to the autodocs.
- Add a reference to the paper in docs/source/notes/resources.rst.
- Add a reference to the layer in docs/source/modules/root.rst.

We are going to submit the design paper to the CIKM resource track. If you would like to contribute other models (additional 1-2) we are happy to add you as a co-author.

Bests,

Benedek

2021-06-05 21:45 UTC, benedekrozemberczki commented on torch_geometric_temporal/nn/attention/2sagcn.py
> +def edge2mat(link, num_node):
Can you write this in pure PyTorch?

2021-06-05 21:45 UTC, benedekrozemberczki commented on torch_geometric_temporal/nn/attention/2sagcn.py
> +def normalize_digraph(A):
Can you rewrite this in PyTorch?

2021-06-05 21:45 UTC, benedekrozemberczki commented on torch_geometric_temporal/nn/attention/2sagcn.py
> +    r"""
Can you rewrite this with pure PyTorch?

2021-06-05 21:45 UTC, benedekrozemberczki commented on torch_geometric_temporal/nn/attention/2sagcn.py
> +def edge_index2inward(edge_index):
Can you rewrite this with PyTorch functions?

2021-06-05 21:45 UTC, benedekrozemberczki commented on torch_geometric_temporal/nn/attention/2sagcn.py
> +class unit_gcn(nn.Module):
Class names have camel cases.

2021-06-05 21:45 UTC, benedekrozemberczki commented on torch_geometric_temporal/nn/attention/2sagcn.py
> +class unit_tcn(nn.Module):
Class names have camelcasing - UnitTCN

2021-06-05 21:45 UTC, benedekrozemberczki commented on torch_geometric_temporal/nn/attention/2sagcn.py
> +def conv_init(conv):
Move init to private class method

2021-06-05 21:45 UTC, benedekrozemberczki commented on torch_geometric_temporal/nn/attention/2sagcn.py
> +def bn_init(bn, scale):
Move init to private class method.

2021-06-05 21:45 UTC, benedekrozemberczki commented on torch_geometric_temporal/nn/attention/2sagcn.py
> +def conv_branch_init(conv, branches):
Move init to private class method.

2021-06-05 21:45 UTC, benedekrozemberczki commented on torch_geometric_temporal/nn/attention/2sagcn.py
> +    def get_adjacency_matrix(self):
Please specify type of return value.

2021-06-05 21:45 UTC, benedekrozemberczki commented on torch_geometric_temporal/nn/attention/2sagcn.py
> +def get_spatial_graph(num_node, self_link, inward, outward):
Please rewrite in PyTorch.

2021-06-05 21:45 UTC, benedekrozemberczki commented on torch_geometric_temporal/nn/attention/2sagcn.py
> +        inter_channels = out_channels // coff_embedding
Please break up the init to submethods. Use private submethods for meaningful subunits of code.

2021-06-05 21:45 UTC, benedekrozemberczki commented on torch_geometric_temporal/nn/attention/2sagcn.py
> +    def __init__(self, in_channels:int, out_channels:int, A:torch.FloatTensor, coff_embedding:int=4, num_subset:int=3, adaptive: bool=True, attention: bool=True):
Please break up the line with linting - https://pypi.org/project/pylint/.

2021-06-05 21:45 UTC, benedekrozemberczki commented on torch_geometric_temporal/nn/attention/2sagcn.py
> +    def forward(self, x):
Please add private methods to break up the forward pass.

2021-06-05 21:45 UTC, benedekrozemberczki commented on torch_geometric_temporal/nn/attention/2sagcn.py
> +class TCN_GCN_unit(nn.Module):
Add Camelcasing name.

2021-06-05 21:45 UTC, benedekrozemberczki commented on torch_geometric_temporal/nn/attention/2sagcn.py
> +    def __init__(self, in_channels:int, out_channels:int, edge_index:torch.LongTensor, num_nodes:int, stride:int=1, residual:bool=True, adaptive:bool=True, attention:bool=True):
Please break the line up. Hard to read.

2021-06-05 21:45 UTC, benedekrozemberczki commented on torch_geometric_temporal/nn/attention/2sagcn.py
> +        self.graph = Graph(self.edge_index, self.num_nodes)
Remove multiple spaces.

2021-06-05 21:45 UTC, benedekrozemberczki commented on torch_geometric_temporal/nn/attention/2sagcn.py
> +if __name__ == "__main__":
We write separate test for doing some sanity checks in the test folder. Test method names start with test. This way we can check the coverage of the test.

2021-06-05 21:45 UTC, benedekrozemberczki commented on torch_geometric_temporal/nn/attention/2sagcn.py
> +if __name__ == "__main__":
Please remove this.

2021-06-06 11:10 UTC, alexriedel1 commented
> Dear Alex,
> 
> 🎇 Thank you for contributing! It is really appreciated, do not worry - it is a really high quality contribution 👍. Please check the following things (you will have to add modifications in a number of places, not just the py file):
> 
> * Modify the init file of attention models.
> * Run through your py file pylint.
> * The docstring should contain default hyperparameter values e.g. kernel_size: int=9.
> * Please write tests in the test folder.
> * Add the paper to the readme - give reference to the autodocs.
> * Add a reference to the paper in docs/source/notes/resources.rst.
> * Add a reference to the layer in docs/source/modules/root.rst.
> 
> We are going to submit the design paper to the CIKM resource track. If you would like to contribute other models (additional 1-2) we are happy to add you as a co-author.
> 
> Bests,
> 
> Benedek

Alright thanks a lot! I've just commited the required changes. I'd be happy to add some more models soon and being considered as co-author :)

2021-06-06 22:49 UTC, merged

2021-06-06 23:08 UTC, benedekrozemberczki commented
Dear Alex,

Merged the PR! There was a minor fix needed for the test, but now it runs with CI and the docs also pass. We will have a research meeting on Tuesday, about the paper submission. If you drop me an e-mail at: benedek.rozemberczki@gmail.com I can send you an invite. Do you have other models in mind?

Bests,

Benedek

2021-06-07 08:23 UTC, alexriedel1 commented
> Dear Alex,
> 
> Merged the PR! There was a minor fix needed for the test, but now it runs with CI and the docs also pass. We will have a research meeting on Tuesday, about the paper submission. If you drop me an e-mail at: [benedek.rozemberczki@gmail.com](mailto:benedek.rozemberczki@gmail.com) I can send you an invite. Do you have other models in mind?
> 
> Bests,
> 
> Benedek

Thanks Benedek! I'll send you an email, plus I'm planning to add this skeleton based action recognition model MS-3GD https://arxiv.org/abs/2003.14111 (one of the highest scoring in benchmarks for graph based action recognition that also make sense to apply in other tasks...)